spring:
  datasource:
    url: jdbc:hsqldb:mem:tasksdb
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
      roles: USER
